version: "3.7"

# See https://stackoverflow.com/questions/29261811/use-docker-compose-env-variable-in-dockerbuild-file
services:
  webui:
    build:
      context: ./web
      dockerfile: Dockerfile.prod
    container_name: app-prod  
    ports:
      - "80:1337"
